- name: "openai/@cf/deepseek-ai/deepseek-r1-distill-qwen-32b"
  edit_format: diff
  use_repo_map: true
  reminder: user
  examples_as_sys_msg: true
  extra_params:
    temperature: 0.6
    top_p: 0.95
  caches_by_default: true
  streaming: true
  use_temperature: true
  use_system_prompt: true
